version: '3.7'

services:
  web:
    build:
      context: .
    ports:
      - 1111

  cypress:
    build:
      context: .
      dockerfile: cypress/Dockerfile
    depends_on:
      - web
    command: |
      --config baseUrl=http://web:1111
      --spec cypress/integration/web-demo/test.js