version: '3.9'
services:
  e2e_1:
    context: .
      dockerfile: cypress/Dockerfile
      args: # build time
        - buildversion=1
    # container_name: cypress1
    command: --spec "cypress/integration/tricky/wait.js" --env "viewport=mobile"
    volumes:
      - ./cypress/results:/opt/cypress-demo/cypress/results
    image: cypress-demo

  e2e_2:
    image: danrusu/cypress-demo
    # container_name: cypress2
    command: --spec "cypress/integration/tricky/fail.js"
    volumes:
      - ./cypress/results:/opt/cypress-demo/cypress/results

  e2e_3:
    image: danrusu/cypress-demo
    # container_name: cypress3
    command: --spec "cypress/integration/tricky/fail.js"
    volumes:
      - ./cypress/results:/opt/cypress-demo/cypress/results

  e2e_4:
    image: danrusu/cypress-demo
    # container_name: cypress4
    command: --spec "cypress/integration/tricky/wait.js"
    volumes:
      - ./cypress/results:/opt/cypress-demo/cypress/results

  e2e_5:
    image: danrusu/cypress-demo
    # container_name: cypress5
    command: --spec "cypress/integration/tricky/wait.js"
    volumes:
      - ./cypress/results:/opt/cypress-demo/cypress/results
