name: Cypress Docker

on: 
  workflow_dispatch:
  
jobs:

  e2e-tests: 
    name:  ${{ matrix.store }}-test 
    runs-on: ubuntu-latest
    #container: cypress/browsers:node14.17.0-chrome91-ff89
    container: cypress/included:9.2.0

    strategy:
      fail-fast: true
      matrix: 
        store: [gb]

    steps:

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Cypress Tests
        id: cypres-tests
        uses: cypress-io/github-action@v2        
        with:
          install-command: |
            npm install cypress-cucumber-preprocessor@4.2.0 mocha@9.1.1 mocha-junit-reporter@2.0.0
          browser: chrome
          command: echo '@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@'
          #spec: cypress/integration/tricky/env-test.js
        env:
          CYPRESS_store: ${{ matrix.store }}