name: Cypress Docker

on: 
  workflow_dispatch:
  
jobs:

  e2e-tests: 
    name:  ${{ matrix.store }}-test 
    runs-on: ubuntu-latest
    #container: cypress/browsers:node14.17.0-chrome91-ff89
    container: cypress/included:9.2.0

    strategy:
      fail-fast: true
      matrix: 
        store: [gb]

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: my-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - run: npm i cypress
      
      - name: Cypress Tests
        uses: cypress-io/github-action@v2   
        with:  
          install: false
          spec: cypress/integration/tricky/env-test.js
        env:
          CYPRESS_store: ${{ matrix.store }}