name: Cypress All Stores

on: 
  workflow_dispatch:
    inputs:
    
      os:
        type: choice
        description: store
        required: true
        options:
          - 'ubuntu-20.04'
          - 'macos-10.15'
          - 'windows-2022'
          - 'windows-2019'
      
      browser:
        type: choice
        description: store
        required: true
        options:
          - 'chrome'
          - 'firefox'
          - 'edge'
                
jobs:
  cypress-run:
    name:  ${{ matrix.store }} | ${{ github.event.inputs.browser }} | ${{ github.event.inputs.os }}
    runs-on: ${{ github.event.inputs.os }}
    
    strategy:
      matrix:
        store: [gb, es]
      fail-fast: true
    
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
    
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: ${{ github.event.inputs.browser }}
          spec: cypress/integration/tricky/SimpleCalculator.feature
        env:
          CYPRESS_store: ${{ matrix.store }}
          
          
