name: Cypress All Stores

on: 
  workflow_dispatch:
    inputs:
    
      os:
        type: choice
        description: store
        required: true
        options:
          - 'ubuntu-20.04'
          - 'macos-10.15'
          - 'windows-2022'
          - 'windows-2019'
      
      browser:
        type: choice
        description: store
        required: true
        options:
          - 'chrome'
          - 'firefox'
          - 'edge'
                
jobs:
  cypress-run:
    name:  ${{ matrix.store }}-${{ github.event.inputs.browser }}-${{ github.event.inputs.os }}-test
    runs-on: ${{ github.event.inputs.os }}
    
    strategy:
      fail-fast: false
      matrix:
        store: [gb, es]
    
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: ${{ github.event.inputs.browser }}
          spec: cypress/integration/SimpleCalculator.feature
        env:
          CYPRESS_store: ${{ matrix.store }}
          
          
