name: Cypress

on: 
  workflow_dispatch:
    inputs:
    
      os:
        type: choice
        description: store
        required: true
        options:
          - 'ubuntu-20.04'
          - 'windows:latest'
      
      browser:
        type: choice
        description: store
        required: true
        options:
          - 'chrome'
          - 'firefox'
          
      store:
        type: choice
        description: store
        required: true
        options:
          - 'gb'
          - 'es'
                
jobs:
  cypress-run:
    name: E2E tests | ${{ github.event.inputs.os }} | ${{ github.event.inputs.browser }} | ${{ github.event.inputs.store }} | 
    runs-on: ${{ github.event.inputs.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: ${{ github.event.inputs.browser }}
          spec: cypress/integration/tricky/env-test.js
        env:
          store: ${{ github.event.inputs.store }}
          
          
