name: Cypress Docker

on: 
  workflow_dispatch:
  
jobs:

  e2e-tests: 
    name:  ${{ matrix.store }}-test 
    runs-on: ubuntu-latest
    #container: cypress/browsers:node14.17.0-chrome91-ff89
    container: cypress/included:9.2.0

    strategy:
      fail-fast: false
      matrix: 
        store: [gb, fr, de, ch, nl, es]

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      # - uses: actions/cache@v2
      #   with:
      #     path: |
      #       ~/.cache/Cypress
      #       node_modules
      #     key: my-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      # - name: Install Dependencies
      #   run: npm i cypress@9.2.0
      
      - name: Cypress Tests
        uses: cypress-io/github-action@v2   
        with:  
          install: false
          spec: cypress/integration/tricky/env-test.js
        env:
          CYPRESS_store: ${{ matrix.store }}