name: Custom Docker Action

on: 
  workflow_dispatch:
  
jobs:
  cypress-included:
    runs-on: ubuntu-latest
    name: cypress
    steps:
      - name: Hello world action step
        id: hello
        uses: danrusu/.github/actions/cypress@v1
        with:
          spec: 'Mona the Octocat'