name: Custom Docker Action

on: 
  workflow_dispatch:
  
jobs:
  cypress-included:
    runs-on: ubuntu-latest
    name: cypress
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: ls -a
      - name: Test
        id: test
        uses: ./cypress
        with:
          spec: 'Mona the Octocat'