name: Custom Docker Action

on: 
  workflow_dispatch:
  
jobs:
  cypress-included:
    runs-on: ubuntu-latest
    name: cypress
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        id: test
        uses: ./.github/actions/cypress@v1
        with:
          spec: 'Mona the Octocat'