name: Cypress Included

on: 
  workflow_dispatch:
    inputs:
    
      os:
        type: choice
        description: store
        required: true
        options:
          - 'ubuntu-20.04'
          - 'macos-10.15'
          - 'windows-2022'
          - 'windows-2019'
      
      browser:
        type: choice
        description: store
        required: true
        options:
          - 'chrome'
          - 'firefox'
          - 'edge'
          
      store:
        type: choice
        description: store
        required: true
        options:
          - 'gb'
          - 'es'
                
jobs:
  cypress-run:
    name: E2E-tests-${{ github.event.inputs.os }}-${{ github.event.inputs.browser }}-${{ github.event.inputs.store }} | 
    runs-on: ${{ github.event.inputs.os }}
    container: cypress/browsers:node12.18.3-chrome87-ff82
    
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
    
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: ${{ github.event.inputs.browser }}
          spec: cypress/integration/tricky/env-test.js
        env:
          CYPRESS_store: ${{ github.event.inputs.store }}
          
          
